### ISSUE TITLE
Usability

### ISSUE THREAD

**Issue by firmai** [HPI-Information-Systems/AutoTSAD#1]
This could be a great package, looking forward to the development, particularly would be interested in it, if I can give it data and it can give me some dataframe output. Well done.

**Comment by SebastianSchmidl** [comment]
AutoTSAD already has a CLI. You can execute AutoTSAD by providing a path to a CSV file, and it will create a `scores.csv`-file within a `results/select-<dataset_id>-<selection_strategy>`-folder. See the [usage section](https://github.com/HPI-Information-Systems/AutoTSAD?tab=readme-ov-file#usage) of the README. Does this solve your problem?

```bash
autotsad run --config-path autotsad.yaml data/timeeval/GutenTAG/ecg-diff-count-1.csv
```

AutoTSAD does not provide a Python-API. I am not planning to add one, either. For reference, you can find the main function in this file: https://github.com/HPI-Information-Systems/AutoTSAD/blob/main/autotsad/system/main.py

**Comment by firmai** [comment]
Yeah you are right, it probably needs a Python api, okay no worries, good luck anyways.
